In [1]:
# simple linear Regression y=mx+c
# multi linear Regression y=m1x1 + m2x2 +m3x3 + ........mnxn+c

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Titanic-Dataset.csv')

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [26]:
df=df.drop(['PassengerId','Name','Ticket'],axis=1)

KeyError: "['PassengerId', 'Name', 'Ticket'] not found in axis"

In [28]:
(df.isnull().sum()/len(df))*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Cabin       77.104377
Embarked     0.224467
dtype: float64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Sex       891 non-null    object
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64
 5   Parch     891 non-null    int64
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object
 8   Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB

In [32]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [34]:
df.info

<bound method DataFrame.info of      Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]>

In [36]:
df=df.drop('Cabin',axis=1)

In [38]:
(df.isnull().sum()/len(df))*100

Survived     0.000000
Pclass       0.000000
Sex          0.000000
Age         19.865320
SibSp        0.000000
Parch        0.000000
Fare         0.000000
Embarked     0.224467
dtype: float64

In [40]:
df['Age']=df['Age'].fillna(round(df['Age'].mean()))

In [42]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [44]:
df['Embarked']=df['Embarked'].fillna('S')

In [46]:
df

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female  30.0      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [48]:
df=pd.get_dummies(data=df,columns=['Sex','Embarked'],dtype=int,drop_first=True)

In [50]:
df

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,7.2500,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0
2,1,3,26.0,0,0,7.9250,0,0,1
3,1,1,35.0,1,0,53.1000,0,0,1
4,0,3,35.0,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,1,0,1
887,1,1,19.0,0,0,30.0000,0,0,1
888,0,3,30.0,1,2,23.4500,0,0,1
889,1,1,26.0,0,0,30.0000,1,0,0
890,0,3,32.0,0,0,7.7500,1,1,0

In [52]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [56]:
x.shape

(891, 8)

In [57]:
x_train.shape

(712, 8)

In [58]:
x_test.shape

(179, 8)

In [59]:
len(y_train)

712

In [60]:
len(y_test)

179

In [68]:
from sklearn.linear_model import LogisticRegression

In [69]:
lr=LogisticRegression()

In [70]:
lr.fit(x_train,y_train)

C:\Users\cvsaf\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [71]:
lr.coef_

array([[-1.15285381e+00, -5.06823866e-02, -3.82332501e-01,
        -3.84262378e-02,  1.89821864e-03, -2.67215949e+00,
         2.77549323e-01, -1.62728323e-02]])

In [88]:
lr.intercept_

array([5.39968167])

In [90]:
y_pred_train=lr.predict(x_train)

In [92]:
y_pred_test=lr.predict(x_test)

In [94]:
from sklearn.metrics import classification_report

In [96]:
print(classification_report(y_train,y_pred_train))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84       433
           1       0.75      0.74      0.75       279

    accuracy                           0.80       712
   macro avg       0.79      0.79      0.79       712
weighted avg       0.80      0.80      0.80       712

In [98]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81       116
           1       0.66      0.62      0.64        63

    accuracy                           0.75       179
   macro avg       0.73      0.72      0.73       179
weighted avg       0.75      0.75      0.75       179

In [100]:
x.columns

Index(['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Sex_male', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [ ]:
pclass=int(input('Please enter P class here:'))
age=int(input('Please enter Age here:'))
sibsp=int(input('Please enter SibSp here:'))
parch=int(input('Please enter Parch here:'))
fare=int(input('Please enter Fare here:'))
male=(input('Are you male'))
if male=='yes':
    male=1
else:
    male=0
embarked_q=(input('Did you embrak from Queenstown'))
if embarked_q=='yes':
    embarked_q=1
else:
    embarked_q=0

  
embarked_s=(input('Did you embrak from Southampton'))
if embarked_s=='yes':
    embarked_s=1
else:
    embarked_s=0
user_input=np.array([pclass,age,sibsp,parch,male,fare,embarked_q,embarked_s]).reshape(1,-1)
if lr.predict(user_input)==0:
    print('RIP! You will not survive')
else:
    print('Hooray! You will survive')